# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-25 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0007_auto_20191025_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='username',
            new_name='user',
        ),
    ]
