# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-25 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0009_project_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='photos/default.jpg', upload_to='photos/'),
        ),
    ]
